# Generated by Django 2.1.1 on 2018-09-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=128, verbose_name='问题标题')),
                ('answer_text', models.TextField(verbose_name='回答内容')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('end_time', models.DateField(auto_created=True, default=None, verbose_name='实际结束时间')),
                ('all_users_number', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='参与人数')),
                ('all_mission_number', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='总任务数')),
                ('process', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='项目进度')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名')),
                ('describe', models.TextField(default='该项目暂无描述', verbose_name='项目描述')),
                ('status', models.CharField(default='筹备状态', max_length=128, verbose_name='项目状态')),
                ('start_time', models.DateField(verbose_name='项目开始日期')),
                ('pre_end_time', models.DateField(verbose_name='预计结束时间')),
                ('job_start', models.TimeField(verbose_name='上班时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCalendar',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('job_hour', models.PositiveIntegerField(default=0, verbose_name='工作时间')),
                ('week_number', models.CharField(max_length=128, verbose_name='星期数')),
                ('is_job_day', models.BooleanField(verbose_name='是否为工作日')),
                ('per_hour_money', models.PositiveIntegerField(verbose_name='每小时成本')),
                ('date_time', models.DateTimeField(verbose_name='日期')),
                ('job_log', models.TextField(verbose_name='工作日志')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '项目日历',
                'verbose_name_plural': '项目日历',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('download_times', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='下载记录')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='文件名')),
                ('description', models.TextField(verbose_name='文件描述')),
                ('url', models.FileField(upload_to='uploads/', verbose_name='文件')),
                ('upload_user_name', models.CharField(max_length=128, verbose_name='上传人名')),
                ('project_name', models.CharField(max_length=128, verbose_name='所属项目名')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('exit_time', models.TimeField(auto_created=True, default=None, verbose_name='退出时间')),
                ('member_cost', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='成本')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, verbose_name='用户名')),
                ('project_name', models.CharField(max_length=128, verbose_name='项目名')),
                ('member_power', models.CharField(choices=[(0, '成员'), (1, '管理员'), (2, '项目主')], default=0, max_length=128, verbose_name='权限')),
                ('join_time', models.TimeField(auto_now_add=True, verbose_name='加入时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目ID')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMission',
            fields=[
                ('end_time', models.DateTimeField(auto_created=True, default=None, verbose_name='结束时间')),
                ('mission_weight', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='任务权重')),
                ('mission_process', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='任务进度')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mission_test', models.TextField(verbose_name='任务内容')),
                ('mission_title', models.CharField(max_length=128, verbose_name='任务标题')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('pre_end_time', models.TimeField(verbose_name='预计结束时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('belong_mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_belong_to', to='app_home.ProjectMission', verbose_name='所属任务')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.ProjectMember', verbose_name='所属项目成员')),
                ('pre_mission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='it_pre', to='app_home.ProjectMission', verbose_name='前驱任务')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目任务',
                'verbose_name_plural': '项目任务',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128, verbose_name='资源类型')),
                ('description', models.CharField(max_length=128, verbose_name='资源描述')),
                ('cost', models.PositiveIntegerField(verbose_name='资源成本')),
                ('use_resource', models.PositiveIntegerField(verbose_name='已用资源')),
                ('no_use_resource', models.PositiveIntegerField(verbose_name='未用资源')),
                ('resource_unit', models.CharField(max_length=128, verbose_name='单位')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.ProjectMission', verbose_name='所属项目成员ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目资源',
                'verbose_name_plural': '项目资源',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('end_time', models.DateTimeField(auto_created=True, default=None, verbose_name='完成时间')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('answer_number', models.PositiveIntegerField(verbose_name='回答数')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('new_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Question', verbose_name='追答问题id')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('project_name', models.CharField(auto_created=True, default=None, max_length=128, verbose_name='项目名')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=128, verbose_name='状态')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '问题状态',
                'verbose_name_plural': '问题状态',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('project_name', models.CharField(auto_created=True, default=None, max_length=128, verbose_name='项目名')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128, verbose_name='类型')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '问题类型',
                'verbose_name_plural': '问题类型',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('location', models.CharField(auto_created=True, default='未知', max_length=128, verbose_name='所在地')),
                ('signature', models.TextField(auto_created=True, default='这个家伙很懒懒', verbose_name='个人简介')),
                ('deadline', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='即将到期通知数')),
                ('new_mission', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='新任务通知数')),
                ('answer_notice', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='回答通知数')),
                ('un_answer', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='未回答问题数')),
                ('notice', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='通知数')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('true_name', models.CharField(max_length=128, verbose_name='真实姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('head_icon', models.ImageField(upload_to='', verbose_name='头像')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('value_time', models.DateField(auto_created=True, verbose_name='适用时间')),
                ('friday', models.BooleanField(auto_created=True, default=True, verbose_name='周五是否上班')),
                ('thursday', models.BooleanField(auto_created=True, default=True, verbose_name='周四是否上班')),
                ('wednesday', models.BooleanField(auto_created=True, default=True, verbose_name='周三是否上班')),
                ('tuesday', models.BooleanField(auto_created=True, default=True, verbose_name='周二是否上班')),
                ('monday', models.BooleanField(auto_created=True, default=True, verbose_name='周一是否上班')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('saturday', models.BooleanField(default=True, verbose_name='周六是否上班')),
                ('sunday', models.BooleanField(default=True, verbose_name='周日是否上班')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '都那些天上班',
                'verbose_name_plural': '都那些天上班',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questioner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='提问人'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.QuestionStatus', verbose_name='所属问题状态'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.QuestionType', verbose_name='所属问题类型'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.ProjectMember', verbose_name='所属项目成员ID'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='mission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.ProjectMission', verbose_name='所属任务ID'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目ID'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='所属用户ID'),
        ),
        migrations.AddField(
            model_name='projectcalendar',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.ProjectMission', verbose_name='所属项目成员ID'),
        ),
        migrations.AddField(
            model_name='projectcalendar',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='projectcalendar',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.Question', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.User', verbose_name='所属用户'),
        ),
    ]
