# Generated by Django 2.1.1 on 2018-10-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('code', models.PositiveSmallIntegerField(verbose_name='验证码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('f_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='head_icon',
            field=models.ImageField(upload_to='uploads/', verbose_name='头像'),
        ),
    ]
